package com.mmall.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class SysDept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.ID
     *
     * @mbggenerated
     */

    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.PARENT_ID
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.LEVELS
     *
     * @mbggenerated
     */
    private String levels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.SEQ
     *
     * @mbggenerated
     */
    private Long seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.OPERATOR_TIME
     *
     * @mbggenerated
     */
    private Date operatorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_DEPT.OPERATOR_IP
     *
     * @mbggenerated
     */
    private String operatorIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.ID
     *
     * @return the value of SYS_DEPT.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.ID
     *
     * @param id the value for SYS_DEPT.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.NAME
     *
     * @return the value of SYS_DEPT.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.NAME
     *
     * @param name the value for SYS_DEPT.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.PARENT_ID
     *
     * @return the value of SYS_DEPT.PARENT_ID
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.PARENT_ID
     *
     * @param parentId the value for SYS_DEPT.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.LEVELS
     *
     * @return the value of SYS_DEPT.LEVELS
     *
     * @mbggenerated
     */
    public String getLevels() {
        return levels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.LEVELS
     *
     * @param levels the value for SYS_DEPT.LEVELS
     *
     * @mbggenerated
     */
    public void setLevels(String levels) {
        this.levels = levels == null ? null : levels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.SEQ
     *
     * @return the value of SYS_DEPT.SEQ
     *
     * @mbggenerated
     */
    public Long getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.SEQ
     *
     * @param seq the value for SYS_DEPT.SEQ
     *
     * @mbggenerated
     */
    public void setSeq(Long seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.REMARK
     *
     * @return the value of SYS_DEPT.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.REMARK
     *
     * @param remark the value for SYS_DEPT.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.OPERATOR
     *
     * @return the value of SYS_DEPT.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.OPERATOR
     *
     * @param operator the value for SYS_DEPT.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.OPERATOR_TIME
     *
     * @return the value of SYS_DEPT.OPERATOR_TIME
     *
     * @mbggenerated
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.OPERATOR_TIME
     *
     * @param operatorTime the value for SYS_DEPT.OPERATOR_TIME
     *
     * @mbggenerated
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_DEPT.OPERATOR_IP
     *
     * @return the value of SYS_DEPT.OPERATOR_IP
     *
     * @mbggenerated
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_DEPT.OPERATOR_IP
     *
     * @param operatorIp the value for SYS_DEPT.OPERATOR_IP
     *
     * @mbggenerated
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }
}