package com.mmall.model;

public class SysLogWithBLOBs extends SysLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.OLD_VALUE
     *
     * @mbggenerated
     */
    private String oldValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.NEW_VALUE
     *
     * @mbggenerated
     */
    private String newValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.OLD_VALUE
     *
     * @return the value of SYS_LOG.OLD_VALUE
     *
     * @mbggenerated
     */
    public String getOldValue() {
        return oldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.OLD_VALUE
     *
     * @param oldValue the value for SYS_LOG.OLD_VALUE
     *
     * @mbggenerated
     */
    public void setOldValue(String oldValue) {
        this.oldValue = oldValue == null ? null : oldValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.NEW_VALUE
     *
     * @return the value of SYS_LOG.NEW_VALUE
     *
     * @mbggenerated
     */
    public String getNewValue() {
        return newValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.NEW_VALUE
     *
     * @param newValue the value for SYS_LOG.NEW_VALUE
     *
     * @mbggenerated
     */
    public void setNewValue(String newValue) {
        this.newValue = newValue == null ? null : newValue.trim();
    }
}