package com.mmall.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class SysRoleAcl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_ACL.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_ACL.ROLE_ID
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_ACL.ACL_ID
     *
     * @mbggenerated
     */
    private Long aclId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_ACL.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_ACL.OPERATOR_TIME
     *
     * @mbggenerated
     */
    private Date operatorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_ACL.OPERATOR_IP
     *
     * @mbggenerated
     */
    private String operatorIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_ACL.ID
     *
     * @return the value of SYS_ROLE_ACL.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_ACL.ID
     *
     * @param id the value for SYS_ROLE_ACL.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_ACL.ROLE_ID
     *
     * @return the value of SYS_ROLE_ACL.ROLE_ID
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_ACL.ROLE_ID
     *
     * @param roleId the value for SYS_ROLE_ACL.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_ACL.ACL_ID
     *
     * @return the value of SYS_ROLE_ACL.ACL_ID
     *
     * @mbggenerated
     */
    public Long getAclId() {
        return aclId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_ACL.ACL_ID
     *
     * @param aclId the value for SYS_ROLE_ACL.ACL_ID
     *
     * @mbggenerated
     */
    public void setAclId(Long aclId) {
        this.aclId = aclId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_ACL.OPERATOR
     *
     * @return the value of SYS_ROLE_ACL.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_ACL.OPERATOR
     *
     * @param operator the value for SYS_ROLE_ACL.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_ACL.OPERATOR_TIME
     *
     * @return the value of SYS_ROLE_ACL.OPERATOR_TIME
     *
     * @mbggenerated
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_ACL.OPERATOR_TIME
     *
     * @param operatorTime the value for SYS_ROLE_ACL.OPERATOR_TIME
     *
     * @mbggenerated
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_ACL.OPERATOR_IP
     *
     * @return the value of SYS_ROLE_ACL.OPERATOR_IP
     *
     * @mbggenerated
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_ACL.OPERATOR_IP
     *
     * @param operatorIp the value for SYS_ROLE_ACL.OPERATOR_IP
     *
     * @mbggenerated
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }
}