package com.mmall.model;

import java.util.Date;

public class SysRoleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_USER.ID
     *
     * @mbggenerated
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_USER.ROLE_ID
     *
     * @mbggenerated
     */
    private Short roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_USER.USER_ID
     *
     * @mbggenerated
     */
    private Short userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_USER.OPERATOR
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_USER.OPERATOR_TIME
     *
     * @mbggenerated
     */
    private Date operatorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLE_USER.OPERATOR_IP
     *
     * @mbggenerated
     */
    private String operatorIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_USER.ID
     *
     * @return the value of SYS_ROLE_USER.ID
     *
     * @mbggenerated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_USER.ID
     *
     * @param id the value for SYS_ROLE_USER.ID
     *
     * @mbggenerated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_USER.ROLE_ID
     *
     * @return the value of SYS_ROLE_USER.ROLE_ID
     *
     * @mbggenerated
     */
    public Short getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_USER.ROLE_ID
     *
     * @param roleId the value for SYS_ROLE_USER.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(Short roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_USER.USER_ID
     *
     * @return the value of SYS_ROLE_USER.USER_ID
     *
     * @mbggenerated
     */
    public Short getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_USER.USER_ID
     *
     * @param userId the value for SYS_ROLE_USER.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Short userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_USER.OPERATOR
     *
     * @return the value of SYS_ROLE_USER.OPERATOR
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_USER.OPERATOR
     *
     * @param operator the value for SYS_ROLE_USER.OPERATOR
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_USER.OPERATOR_TIME
     *
     * @return the value of SYS_ROLE_USER.OPERATOR_TIME
     *
     * @mbggenerated
     */
    public Date getOperatorTime() {
        return operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_USER.OPERATOR_TIME
     *
     * @param operatorTime the value for SYS_ROLE_USER.OPERATOR_TIME
     *
     * @mbggenerated
     */
    public void setOperatorTime(Date operatorTime) {
        this.operatorTime = operatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLE_USER.OPERATOR_IP
     *
     * @return the value of SYS_ROLE_USER.OPERATOR_IP
     *
     * @mbggenerated
     */
    public String getOperatorIp() {
        return operatorIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLE_USER.OPERATOR_IP
     *
     * @param operatorIp the value for SYS_ROLE_USER.OPERATOR_IP
     *
     * @mbggenerated
     */
    public void setOperatorIp(String operatorIp) {
        this.operatorIp = operatorIp == null ? null : operatorIp.trim();
    }
}