package com.mmall.dao;

import com.mmall.model.SysAcl;

import java.util.List;

public interface SysAclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACL
     *
     * @mbggenerated
     */
    int insert(SysAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACL
     *
     * @mbggenerated
     */
    int insertSelective(SysAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACL
     *
     * @mbggenerated
     */
    SysAcl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAcl record);

    List<SysAcl> findAll();
}