package com.mmall.dao;

import com.mmall.model.SysAclModule;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysAclModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACL_MODULE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACL_MODULE
     *
     * @mbggenerated
     */
    int insert(SysAclModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACL_MODULE
     *
     * @mbggenerated
     */
    int insertSelective(SysAclModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACL_MODULE
     *
     * @mbggenerated
     */
    SysAclModule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACL_MODULE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysAclModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ACL_MODULE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysAclModule record);

    int countByNameAndParentId(@Param("parentId") Long parentId, @Param("name") String name, @Param("id") Long id);

    List<SysAclModule> findAll();

    int checkHasChildren(String level);
}