package com.mmall.dao;

import com.mmall.model.SysRoleAcl;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysRoleAclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_ACL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_ACL
     *
     * @mbggenerated
     */
    int insert(SysRoleAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_ACL
     *
     * @mbggenerated
     */
    int insertSelective(SysRoleAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_ACL
     *
     * @mbggenerated
     */
    SysRoleAcl selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_ACL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRoleAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_ACL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRoleAcl record);

    List<Long> getAclIdListByRoleIdList(@Param("roleIdList") List<Long> roleIdList);

    void deleteByRoleId(Long roleId);

    int batchInsert(@Param("roleAclList") List<SysRoleAcl> roleAclList);
}