package com.mmall.dao;

import com.mmall.model.SysRoleUser;

import java.util.List;

public interface SysRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_USER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_USER
     *
     * @mbggenerated
     */
    int insert(SysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_USER
     *
     * @mbggenerated
     */
    int insertSelective(SysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_USER
     *
     * @mbggenerated
     */
    SysRoleUser selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_ROLE_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRoleUser record);

    List<Long> getRoleIdListByUserId(Long userId);
}